<?php
declare(strict_types=1);
$root='C:/Users/diplk/Documents/amanah/backend';
spl_autoload_register(function($class) use($root) { $file=$root.'/src/'.str_replace('\\','/',substr($class,7)).'.php'; if(is_file($file))require_once $file; });
require_once $root.'/src/Services/PaymentGateway.php';
use Amanah\Infrastructure\Database;
use Amanah\Services\{DonationService,FakePaymentGateway,PaymentGateway,WebhookService,RefundService,CommunicationService};
use Amanah\Security\RateLimiter;
function db():Database {global $root; $d=new Database(new PDO('sqlite::memory:'));$d->pdo()->exec(file_get_contents($root.'/database/schema.sql'));return $d;}
function input(string $key='key1'):array{return ['amount'=>'50','email'=>'audit@example.org','idempotency_key'=>$key];}
function emit(string $name,array $data):void{echo json_encode(['case'=>$name]+$data,JSON_UNESCAPED_SLASHES)."\n";}
function checkout(Database $db,?PaymentGateway $g=null):DonationService{return new DonationService($db,$g??new FakePaymentGateway(),'test','http://localhost',false);}
function pay(Database $db,string $ref,array $extra=[],string $type='payment_succeeded'):void{$body=json_encode(['id'=>uniqid('evt_'),'type'=>$type,'livemode'=>true,'data'=>['donation_reference'=>$ref,'payment_id'=>uniqid('pay_')]+$extra]);(new WebhookService($db,'audit-secret','test'))->handle($body,hash_hmac('sha256',$body,'audit-secret'));}
$d=db();$svc=checkout($d);$a=$svc->checkout(input(),'sessionA');$b=$svc->checkout(array_replace(input(),['amount'=>'150']),'sessionB');emit('checkout_changed_amount_other_session',['same_reference'=>$a['reference']===$b['reference'],'stored_cents'=>$d->fetchOne('SELECT amount_cents FROM donations')['amount_cents']]);
$d=db();$g=new class implements PaymentGateway {public int $calls=0; public function createCheckout(array $d,string $k):array {$this->calls++;throw new RuntimeException('simulated timeout');} public function refund(array $d,int $a,string $k):array{return [];}};$svc=checkout($d,$g);try{$svc->checkout(input(),'s');}catch(Throwable $e){}$retry=$svc->checkout(input(),'s');emit('checkout_retry_timeout',['gateway_calls'=>$g->calls,'retry'=>$retry]);
$d=db();$a=checkout($d)->checkout(input(),'s');pay($d,$a['reference'],['payment_status'=>'unpaid'],'checkout.session.completed');emit('webhook_unpaid_no_amount_currency_live_event_test_config',['donation'=>$d->fetchOne('SELECT status FROM donations'),'ledger_count'=>$d->fetchOne('SELECT COUNT(*) AS n FROM financial_entries')['n']]);
$d=db();$a=checkout($d)->checkout(input(),'s');pay($d,$a['reference']);$id=$d->fetchOne('SELECT id FROM donations')['id'];$d->execute("INSERT INTO users(id,email,password_hash,status,created_at,updated_at) VALUES('actor','actor@example.org','unused','active','2026-09-13','2026-09-13')");$g=new class implements PaymentGateway {public function createCheckout(array $d,string $k):array{return [];}public function refund(array $d,int $a,string $k):array{return ['provider_refund_id'=>'pending-ref','status'=>'pending'];}};$r=(new RefundService($d,$g))->refund($id,'50','refund1','actor');emit('pending_refund',['response'=>$r,'donation_status'=>$d->fetchOne('SELECT status FROM donations')['status'],'ledger_net'=>$d->fetchOne('SELECT SUM(amount_cents) AS n FROM financial_entries')['n']]);
$d=db();$a=checkout($d)->checkout(input(),'s');pay($d,$a['reference']);$id=$d->fetchOne('SELECT id FROM donations')['id'];$d->execute("INSERT INTO users(id,email,password_hash,status,created_at,updated_at) VALUES('actor','actor@example.org','unused','active','2026-09-13','2026-09-13')");$r=new RefundService($d,new FakePaymentGateway());$r->refund($id,'50','refund1','actor');try{$retry=$r->refund($id,'50','refund1','actor');emit('full_refund_retry',['result'=>$retry]);}catch(Throwable $e){emit('full_refund_retry',['exception'=>$e->getMessage()]);}
$d=db();$s=new CommunicationService($d,new RateLimiter($d));$token=$s->subscribe('audit@example.org','127.0.0.1');$s->confirm($token);$before=$d->fetchOne('SELECT status,unsubscribe_token_hash FROM newsletter_subscribers');$s->subscribe('audit@example.org','127.0.0.1');$after=$d->fetchOne('SELECT status,unsubscribe_token_hash FROM newsletter_subscribers');$messages=$d->fetchAll('SELECT payload FROM outbox_messages');$payload=json_decode($messages[1]['payload'],true);emit('newsletter_resubmit',['before'=>$before['status'],'after'=>$after['status'],'new_unsubscribe_token_valid'=>hash('sha256',$payload['unsubscribe_token'])===$after['unsubscribe_token_hash']]);
$d=db();$a=checkout($d)->checkout(input(),'s');$body=json_encode(['id'=>'duplicate_evt','type'=>'payment_succeeded','data'=>['donation_reference'=>$a['reference'],'payment_id'=>'unique_payment','amount_cents'=>5000,'currency'=>'CHF']]);$w=new WebhookService($d,'audit-secret','test');$w->handle($body,hash_hmac('sha256',$body,'audit-secret'));$dupe=$w->handle($body,hash_hmac('sha256',$body,'audit-secret'));emit('webhook_exact_duplicate_control',['duplicate'=>$dupe['duplicate'],'ledger_count'=>$d->fetchOne('SELECT COUNT(*) AS n FROM financial_entries')['n']]);
$d=db();$a=checkout($d)->checkout(input(),'s');try{pay($d,$a['reference'],['amount_cents'=>6000,'currency'=>'CHF']);}catch(Throwable $e){emit('webhook_mismatch_control',['exception'=>$e->getMessage(),'status'=>$d->fetchOne('SELECT status FROM donations')['status'],'persisted_events'=>$d->fetchOne('SELECT COUNT(*) AS n FROM payment_events')['n']]);}
$d=db();$d->execute("INSERT INTO projects(id,slug,title,summary,description,need,editorial_status,operational_status,created_at,updated_at) VALUES('p1','suspended','test','test','test','test','published','suspended','2026-09-13','2026-09-13')");$a=checkout($d)->checkout(input()+['project'=>'suspended'],'s');emit('suspended_project_checkout',['result'=>$a['status'],'project_id'=>$d->fetchOne('SELECT project_id FROM donations')['project_id']]);
$d=db();$a=checkout($d)->checkout(input(),'s');pay($d,$a['reference']);$id=$d->fetchOne('SELECT id FROM donations')['id'];$d->execute("INSERT INTO users(id,email,password_hash,status,created_at,updated_at) VALUES('actor','actor@example.org','unused','active','2026-09-13','2026-09-13')");$g=new class implements PaymentGateway {public function createCheckout(array $d,string $k):array{return [];}public function refund(array $d,int $a,string $k):array{return ['provider_refund_id'=>'pending-'.$k,'status'=>'pending'];}};$r=new RefundService($d,$g);$r->refund($id,'30','pending1','actor');$r->refund($id,'30','pending2','actor');emit('pending_refunds_over_total',['donation_cents'=>5000,'refunds_requested_cents'=>$d->fetchOne('SELECT SUM(amount_cents) n FROM refunds')['n'],'ledger_net'=>$d->fetchOne('SELECT SUM(amount_cents) n FROM financial_entries')['n']]);
